apiVersion: v1
kind: Service

metadata:
  name: react-ros-robot2
  labels:
    app: react-ros-robot2

spec:
  type: NodePort

  selector:
    app: react-ros-robot2

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31779
