apiVersion: apps/v1
kind: Deployment

metadata:
  name: ros2-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ros2-app

  template:
    metadata:
      labels:
        app: ros2-app

    spec:
      containers:
        - name: ros2
          image: ros:humble

          command: ["/bin/bash", "-c"]
          args:
            - "source /opt/ros/humble/setup.bash && sleep infinity"

          volumeMounts:
            - name: shared-storage
              mountPath: /shared

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: react-ros-shared-pvc
